#!/usr/bin/env python3
"""Regenerate data/catalog.js from data/catalog.json so the site works from file:// and static hosts.
data/catalog.json is the source of truth (and the feed the codanomix Shop importer reads)."""
import json, pathlib

root = pathlib.Path(__file__).resolve().parent.parent
feed = json.loads((root / "data" / "catalog.json").read_text())
out = "/* generated by tools/build_catalog_js.py — edit data/catalog.json instead */\n"
out += "window.BNFB_CATALOG = " + json.dumps(feed, ensure_ascii=False, separators=(",", ":")) + ";\n"
(root / "data" / "catalog.js").write_text(out)
print(f"data/catalog.js: {len(feed['works'])} works")
